apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
kind: NetworkPolicy 
apiVersion: networking.k8s.io/v1 
metadata: 
  name: allow-internet-only 
spec: 
  podSelector: {} 
  policyTypes: 
  - Egress 
  egress: 
  - to: 
    - ipBlock: 
        cidr: 0.0.0.0/0 
        except: 
        - 10.0.0.0/14		 
        - 10.4.0.0/20 
