apiVersion: apps/v1
kind: Deployment
metadata:
        name: persistent-layer-deployment
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: project
        template:
                metadata:
                        labels:
                                app: project
                spec:
                        containers:
                                - name: postgres-container
                                  image: postgres:13.1-alpine
                                  imagePullPolicy: "IfNotPresent"
                                  ports:
                                          - containerPort: 5432
                                  envFrom:
                                          - configMapRef:
                                                  name: persistent-layer-config
                                  env:
                                          - name: POSTGRES_PASSWORD
                                            valueFrom:
                                                    secretKeyRef:
                                                            name: persistent-layer-secret
                                                            key: POSTGRES_PASSWORD
                                  volumeMounts:
                                          - name: projectdb
                                            mountPath: /var/lib/postgresql/data
                        volumes:
                                - name: projectdb
                                  persistentVolumeClaim:
                                          claimName: persistent-layer-pvc