apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-pod-admin
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
