apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-admin-pods-global
subjects:
- kind: User
  name: admin2
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: user-pod-admin
  apiGroup: rbac.authorization.k8s.io 
