# app db
apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Values.names.secrets.persistentLayer }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.data.secret.dbpwd }}
---
# tls secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.names.secrets.tls }}
type: kubernetes.io/tls
data:
  # the data is abbreviated in this example
  tls.crt: |
        MIIGCzCCA/OgAwIBAgIUDkDDsxrh4rBJqHBuOgM+VYhCYoswDQYJKoZIhvcNAQEL
        BQAwgZQxCzAJBgNVBAYTAlJPMQ8wDQYDVQQIDAZHYWxhdGkxDzANBgNVBAcMBmdh
        bGF0aTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMQ8wDQYDVQQD
        DAZCb2dkYW4xLzAtBgkqhkiG9w0BCQEWIGFuZHJlaS5ib2dkYW4ubWFyY2VsOTdA
        Z21haWwuY29tMB4XDTIyMDEzMDA5MjkxOFoXDTIzMDEzMDA5MjkxOFowgZQxCzAJ
        BgNVBAYTAlJPMQ8wDQYDVQQIDAZHYWxhdGkxDzANBgNVBAcMBmdhbGF0aTEhMB8G
        A1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMQ8wDQYDVQQDDAZCb2dkYW4x
        LzAtBgkqhkiG9w0BCQEWIGFuZHJlaS5ib2dkYW4ubWFyY2VsOTdAZ21haWwuY29t
        MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAqWQCjf9u6m1Ao1Lm/rl8
        jJsqRgpuSfvVk+aAj3tZ88//yzGl67pfwPxcnnMcKZfEwDcoaujiovZSZV8QH5/i
        QlZEsK/t+J3Ei6UOhh6myTcSUENr6qH291bGWDF8DGN/zrYTTsatskfHr3IA0Egl
        w3NCxUy/AQAIQG2yvfTG6p5JI48gdTnuR8A9b6e13T2ho2rcGPrKqWUqEcGo/ELi
        KVyWHEKZ9+S9Sqm9wdodLHU4MxwXL7DsTTsZAr3+v7bojde4pOU9dwrEWoJqgE4s
        qHUWzvtWckdc+trwPPHODtMd1f2nMtYwk+a2wvRPIwxqUGiEtkrImegYXkMjU32i
        yql22MDF8Z4GNMOgQOuxQTWQ98CXFfNidN7TKzgo+9sAhBT+ba+WM6Tt7eDw4vnZ
        6vGTz3h/VCTlwTeeOYyL6rLBQUnv/qDTMarjDYRq+f3uactpbvRd2IrnXvqxYSvC
        c8k8qcFphsdZU5Zfga60dtDenxLIiviCq3AjuglweyfK2NxbcFxIna4siZkGQ94f
        SkaRtYCloyrntZSIRsd1XyBvJjFiD6i+TjoXvFvM1ZoU/DOe8KqA51uwiQEJmu1B
        Y4RcHo87JzbrZrdZcl4j+G+szF8TfqxzSa/yZXFwNdyAw32gSf8WCXhQnRbSzcYG
        wxGxwgddGtZbNgW6aQBDkoECAwEAAaNTMFEwHQYDVR0OBBYEFPu4bSvT9+FpgbCE
        Ux0qULvJeku0MB8GA1UdIwQYMBaAFPu4bSvT9+FpgbCEUx0qULvJeku0MA8GA1Ud
        EwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBABhLsY3rMqP3G8ydVzmCKG8i
        6NPcWbqVAnOyiBaOp2N2+R7GOW7fCQ69lk1TiKWCkj/s03CtAWkdkxY6slK8mTwG
        KXqJ/Tac4xgYb/tKdpy7qjnZW4tff6PE4j7KaS3vcJOe7XsxjnnFfjJRGTUl+IBm
        H+8iDfaRXlJPAnThZspFz6dxE48GD/Orm4/bhk7Y09ja+kt1edKokLGNcy7gYr7e
        6qTsMAOQaRPiIilaa1rjE3oCR5POuzTzDHHpSAxgX+bKS6zIukRzRSIgoEdjKOYZ
        H5nUhmKGa8jGnhrrA3eMG+U+mts8vCb/JwzgqF8NpTTn+vsfytdrZnHAIRoSbzVp
        2gCJHDaTo1Bzic2Ww0NfVJmR2nc24e7rnlPRaiNbYTHW5g+2/QA2tUVjvjdWP+Ey
        ZGEmlzSM6So7U8hJ56jkqE7rQ9KJVjq7obeoqLIcqnFlINKSqB1oR6psQ6W6Qd4r
        ZfMIDrLz/syXXNAG8qB/bbyFosKhIDIhVRKhUhPxZE7CXz5Kjt3/lQ9CnD3jt0k+
        Q1aYESF68JFMVPd7WJCyJNqox/oGHBEJd420EgbZkgxQhMdJ+DwmzuD9xvwYhdTY
        pP2mwuH2AhusHd+7VEuZnZa84kEYKDhpjT7dW4smcxTUI4zmrSH3jJf5rii4NCOF
        JaJNHHfDB3KpCxym5yXQ
  tls.key: |
        MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQCpZAKN/27qbUCj
        Uub+uXyMmypGCm5J+9WT5oCPe1nzz//LMaXrul/A/Fyecxwpl8TANyhq6OKi9lJl
        XxAfn+JCVkSwr+34ncSLpQ6GHqbJNxJQQ2vqofb3VsZYMXwMY3/OthNOxq2yR8ev
        cgDQSCXDc0LFTL8BAAhAbbK99MbqnkkjjyB1Oe5HwD1vp7XdPaGjatwY+sqpZSoR
        waj8QuIpXJYcQpn35L1Kqb3B2h0sdTgzHBcvsOxNOxkCvf6/tuiN17ik5T13CsRa
        gmqATiyodRbO+1ZyR1z62vA88c4O0x3V/acy1jCT5rbC9E8jDGpQaIS2SsiZ6Bhe
        QyNTfaLKqXbYwMXxngY0w6BA67FBNZD3wJcV82J03tMrOCj72wCEFP5tr5YzpO3t
        4PDi+dnq8ZPPeH9UJOXBN545jIvqssFBSe/+oNMxquMNhGr5/e5py2lu9F3Yiude
        +rFhK8JzyTypwWmGx1lTll+BrrR20N6fEsiK+IKrcCO6CXB7J8rY3FtwXEidriyJ
        mQZD3h9KRpG1gKWjKue1lIhGx3VfIG8mMWIPqL5OOhe8W8zVmhT8M57wqoDnW7CJ
        AQma7UFjhFwejzsnNutmt1lyXiP4b6zMXxN+rHNJr/JlcXA13IDDfaBJ/xYJeFCd
        FtLNxgbDEbHCB10a1ls2BbppAEOSgQIDAQABAoICAC+UD8Oiw5zFIyq81nUl1H4J
        903FEEVnnw3z6JhkpVd+TPLd9yTHLK4gNEOtQXPNVU5IL+oXj9EGLw6aLQU0+3B2
        msSmJcl3RwWSTwoNAfvypAo3ZdB5vcyravrKq3UvXW7KZZHy7EbvMn9tHh1ipnjH
        nzGb5Op6/9ZY+aOxZU3xN8ntIcjLhMpSjO8XxFVoQkaMdVXu243JBJAIPVbd0nib
        sO4vJuAiN6kJFGumwBsEscxpT3ntz/HBb7z9cNiYn6l3tj1axnDxbUWe7Bst2g1X
        Fhj9L8LZmJw9cs0rfh1b3z2ECbqVvv9MBnmr9a56hkIfmWc6ii3wqyeO5BVHbLna
        3VRK1JT6aul7pCo3W75zNudCc9r1M1ApM5HCd6h7pj72/prrDQ2Dn0OncJP1ubK2
        goWNKDzzZz0ChcKYxH4C/mK4TnHc/lxxDePAwc0WWRoLWloxHLyUOi03X2uOoy63
        qua7AMfwAO7J8FC/vJSAOq/qtYMzDSnCE2aHiSL7nu16/vfepgxmQo+VxX/rE/ej
        +5khDKxlg+F0e423x19ky7j08EmAtYFuOhQtFlKh4xm/Ynb9b/i1QO7Dj/fjj9Ta
        8QEs6WGLcVZVI1oXOrwPQfTLtAD9+LI2+p61CW80A6YN+QfROVcB8rnQ9sJoLRAR
        jhGpgWpQYS1z/ymhE9YBAoIBAQDYhrbKTWKuCS/ainn3Z3PQ6bMmFiVW2hXI+c6G
        Y+lYfOvvLn+/ER/33tyAWaIPuPZ9x25OP/UVuPIhTWJyBQQ7DAmLWrtFskOLVHRF
        LXjhnQK+Ohwt/B5s6Qt5C4MnqbP3p70QIz/UayObz4pm77h9Kp5A7SOUBizwxyST
        MOdDMnhYzIsVg8nvf7/UeHy4c/TYYYwp5gAuaHO/Dg92SBajFCtGRqc0gyyU5vWJ
        zLOkbyEGi3ywwkYMH7996bjApC+CSlYpjvZawAdpOYyqjHkPyWY48Y7/C56wOQz9
        uhN1+bnGmwMqD7aYX+imq1oyh6UuLZfy0Rp+c78Wj3BF9aRJAoIBAQDIRXpMPLSO
        TqB3agcZlmB88anwWZdellCrqLO5UMTOoXxfQQzYfSt5tBIQGApsODOIFdz/VV7l
        usQMYB9USA6/2hNFTD+/enilJJ23Uchsco0mfXWMxBwCTtr+opme3wtSZMXkrnus
        YcyWVUvyBv47deubJ6SvzTL3HNNkAcutYrx+71CPcq2GK99YyY30GzgruShiWYoI
        17hRA101g72VkNv641tP3TOd6PutskHjGYMG20qW9rqawHXJAsw1L0bFk3M0PUpF
        RChdrVB4q5bSZfUIv/c3HcqZopH54lr0OlqTUfZ5VWxq/HIUBrIBbMGQxIluu5DX
        BWwuhQK8yYx5AoIBAQDK0YUvAkXI13onr0aH5DOsIPxaVKwtKqL1WmmFoNjWtk0a
        AehPRO8481yALXWMXKknMEO2sFoWOuMzJpVsUB6iYKggDKEWq+BxBm7SzcFJNBV5
        slzrBhpJ0hGZFJuJ74BQHqMOFraXdrQoIsN1oF6jf+Q01Oxan15BO4ibB1fYrdHk
        +9PcF1J0MKmzkBjjflp+xQDRzkulLNoewEDjfqsVnrLaZRwCKEz+PUkKBuDOyfmZ
        c9ccix2qBaMNgnw4lpKZ7J/A1dUVNIK8odeNeX98th42gK59YJkIYKg2krHf9Ed8
        LX9NSuKy4EPAuwkGA+FJ3BNUs2GpySnZLAryvSFhAoIBAQCQ0q09tChdQD6KHAJG
        XpgnwhpB1IfBvrFXcQeGWwH26pAl0cSYSOvHdpAZU0k2OO4K2sSVYAbf2c8ro9cD
        +5eu5ORKmHkA3m+f/HqQtnNY+P1ZeCApSyd2A9AZkzvDx0dIrdbtJ8AHSDHKBKSG
        wMfX984IxQIynxDb4dx71VCUcXId2LFJCoSxIcjBS/97JrPX6m1psZZADr8a1nPw
        3vOZ1Mc/BmphtnQ9HN3jHaTHtQsrSikGQiVvAv4p/fvt+eITvizw+eFbdY47L7mh
        iXPnchNf4HHFSaXYs9cb/LQJKKmXHw49b6iXNTbJhI30udC//1/i04BJ/YHdohH4
        s0cBAoIBAGgwotqkNmtTfKRpOsCke19SvF94VzjcsaQWX1k6kLSZr+IVu7o410fg
        PZwnHloXNSQ2j2WNDkiDUQgF0+adukcJXTnt3WMGZ036GDdAqNaREnmR+QKKDJEp
        47T32W4+KsrvYMXIypoptADZKE5oJApZrRUNo6zdX+1IGgUw7D5DZJNGY0VNV6NJ
        t8ciCo0bh12tmB5Az6J/AQgHN0mlABc8nISMwafyywkt3mDNV+ox6hzyTltKDfhy
        ISiWtcnZmASQeklHsSB9TOlAB3CZVIBkQGPqrkhWbrPEo+iFCOxNqdgqxCfyjfe/
        pMFKWz7SkcsLzBOy3Yl37Len4Q0ubD8=
