# persistent layer
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.services.persistentLayer }}
  labels:
    app: {{ .Values.appLabel.persistentLayer }}
spec:
  type: {{ .Values.services.type.persistentLayer }}
  ports:
    - port: {{ .Values.ports.persistentLayer.servicePort }}
  selector:
    app: {{ .Values.appLabel.persistentLayer }}
---
# rest-api
apiVersion: v1 
kind: Service 
metadata: 
  name: {{ .Values.names.services.restAPI }} 
  labels:
    app: {{ .Values.appLabel.restAPI }}
spec: 
  type: {{ .Values.services.type.restAPI }} 
  ports: 
   - protocol: {{ .Values.services.protocol.restAPI }}  
     port: {{ .Values.ports.restAPI.port }} 
     targetPort: {{ .Values.ports.restAPI.targetPort }} 
  selector: 
    app: {{ .Values.appLabel.restAPI }}
---
# web app
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.services.webApp }}
spec:
  type: {{ .Values.services.type.webApp }}
  ports:
    - protocol: {{ .Values.ports.webApp.protocol | quote }} 
      port: {{ .Values.ports.webApp.port }} 
      targetPort: {{ .Values.ports.webApp.targetPort }} 
  selector:
    app: {{ .Values.appLabel.webApp }}