apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.services.persistentLayer }}
  labels:
    app: {{ .Values.selector.matchLabels.persistentLayer }}
spec:
  type: {{ .Values.services.type.persistentLayer }}
  ports:
    - port: {{ .Values.ports.persistentLayer.servicePort }}
  selector:
    app: {{ .Values.selector.matchLabels.persistentLayer }}
